name: Publish
on:
  release:
    types: [ published ]
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Testing
        run: pnpm run test

      - name: Building
        run: pnpm run build

      - name: Publish to npm
        run: pnpm publish --access public --no-git-checks --registry https://registry.npmjs.org
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
