name: Publish
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
      - run: pnpm install --no-frozen-lockfile

      - name: Test
        run: pnpm run test

      - name: build
        run: pnpm run build

      - name: Create changeset
        run: pnpm run changeset

      - name: Publish to npm registry
        run: pnpm publish --access public
      # - name: Update documentation
      #   run: update-docs.sh

