name: Publish
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile

      - run: pnpm run build
      - run: pnpm run test

      - name: Create changeset
        run: pnpm run changeset

      # Step to publish the new version to the npm registry
      - name: Publish to npm registry
        run: pnpm publish
      # You can add more steps for post-publish actions if needed
      # For example, updating documentation or notifying users
      # - name: Update documentation
      #   run: update-docs.sh

